### ISSUE TITLE
Publish it on PWAThemes.com

### ISSUE THREAD

**Issue by cborodescu** [paulhoughton/react-pwa#2]
Hi Paul, 

This is Ciprian from PWAThemes.com - a marketplace for Progressive Web Apps. I noticed your React & PReact PWAs on GitHub and I wanted to ask if it would be OK with you to publish it on PWAThemes.com as a freebie, mentioning you as an author and all. Looking forward to hearing your thoughts.

**Comment by paulhoughton** [comment]
It's open source, feel free to do whatever you like with them.

However both projects are outdated now as cli's incorporating services workers came out after they were written, they are probably fine for your purposes though.

**Comment by RicSala** [comment]
Hey Paul!

I have take a look at your company, great project!

I was wondering, instead of "plugins" that live above a theme that is not mobile based, why don't you develope a theme that IS mobile first from the beggining?

Doesn't make your web sites slow doing it the way you do?

**Comment by paulhoughton** [comment]
Hi Ric,

I'm not sure I understand? This project is just a simple example of how you might use Material Design Lite with React and service workers to create a progressive web app suitable for mobiles.

Material Design Lite has been deprecated since this project was created, [Preact PWA](https://github.com/paulhoughton/preact-pwa/) is a similar example using [Material Components for the Web](https://github.com/material-components/material-components-web) which produces smaller bundles so will help with performance.

**Comment by RicSala** [comment]
ops! Sorry, I was talking to @cborodescu ! xD
